### ISSUE TITLE
 Missing icu full data

### ISSUE THREAD

**Issue by loicrey** [williarin/docker-images#4]
Hello William.

It seems that your images based on Alpine 3.16 (the one used on Sword) have their ICU packages splitted in two and only the english is installed : https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split and we're not able to use package using Intl for translations (like `twig/intl-extra`)

To fix it, you can add the `icu-data-full` package into your Alpine Dockerfile
`RUN apk add --no-cache icu-data-full`

Regards

**Comment by williarin** [comment]
Hi Loïc, thanks for pointing this out. Instead of adding it to Alpine 3.16, I migrated all PHP images to Alpine 3.18, and added the `icu-data-full` package as well in #5. I've also rebuilt Sword images based on these new images. Does it solve the problem you're having?

**Comment by loicrey** [comment]
Hi William.

I previously solved the problem by adding `RUN apk add --no-cache icu-data-ful` to a custom Dockerfile from your PHP image in my project.
I removed the line, updated to your new PHP image and it's also working.

Thanks for the quick fix !
